### ISSUE TITLE
Infinite loop while calculating scheme

### ISSUE THREAD

**Issue by viktorpovazhuk** [archy-co/l4logic#1]
If we have a loop in a scheme, we will have an infinite loop when trying to calculate the output. It happens because each element of two elements connected in a loop will ask for the output value of another element which depends on the current element's output value and so on.
![infinite_loop](https://user-images.githubusercontent.com/77798403/120164640-721b1500-c203-11eb-877e-e25ea7575d11.png)

**Comment by archy-co** [comment]
Fixed in 034a914a423efb11e80d43bcc1054cf33a701e54, closing.
